export const CREATE = "CREATE"
export const UPDATE = "UPDATE"
export const DELETE = "DELTE"
export const LIKEPOST = "LIKEPOST"
export const FETCH_ALL = "FETCH_ALL"

export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
export const SIGNIN = "SIGNIN"
export const SIGNUP = "SIGNUP"